### ISSUE TITLE
will not run

### ISSUE THREAD

**Issue by jjude80** [gekkowarez/gekkoga#1]
I have tried on 4 different systems to get this to run, but it will not.

this is just a snippet of the output.

No previous run data, starting from scratch!
Starting training with: 4 units
{ StatusCodeError: 500 - "Internal Server Error"
    at new StatusCodeError (/home/jjude/gekko/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/jjude/gekko/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/jjude/gekko/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/jjude/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/jjude/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/jjude/gekko/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',
  error: 'Internal Server Error',
  options:
   { url: 'http://kodi-livingroom:3001/api/backtest',
     json: true,
     body: { gekkoConfig: [Object], data: [Object] },
     headers: { 'Content-Type': 'application/json' },
     timeout: 900000,
     method: 'POST',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },

**Comment by wassimchelfi** [comment]
Hi, i have this error,... I must modify any thing? thks

 xxx POST /api/backtest 500 970ms -

  Error: non-error thrown: Child process has died.

**Comment by generalectric** [comment]
Can you confirm that your DB does in fact have the specified market data for the daterange? Also have you ran the sample-config.js on a valid dataset?

**Comment by jjude80** [comment]
im using Postgresql.  is it compatible? Yes, I have the data range in my database.

**Comment by generalectric** [comment]
@jjude80 did you run sample-config.js on your valid dataset? Are you running gekko 0.5.9?

**Comment by sanitariu** [comment]
I had the same problem:
"Can you confirm that your DB does in fact have the specified market data for the daterange"
- Solves the problem.

**Comment by jjude80** [comment]
I finally got it working.  I just ran it against data from a watcher that has been running for a couple of days, and it worked.  Must have just not had enough data to work before.

**Comment by sanitariu** [comment]
Did you solve the looping non-stop which also raises CPU to 100% ?
