### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by fredericcambon** [gekkowarez/gekkoga#10]
Hi ! I'm getting the following error when testing 

```
Starting GA with epoch populations of 20, running 5 units at a time!
{ RequestError: Error: socket hang up
    at new RequestError (/Users/Grun7/dev/gekko/gekkoga/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/Grun7/dev/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/Grun7/dev/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/Grun7/dev/gekko/gekkoga/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/Grun7/dev/gekko/gekkoga/node_modules/request/request.js:878:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: socket hang up',
  cause: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' },
```

Any idea what it could be ? I'm using the following settings : 

```
const config = {
  stratName: 'XXX',
  gekkoConfig: {
    watch: {
      exchange: 'poloniex',
      currency: 'BTC',
      asset: 'LTC'
    },

    daterange: 'scan',
    simulationBalance: {
      'asset': 1,
      'currency': 1
    },

    slippage: 0.05,
    feeTaker: 0.25,
    feeMaker: 0.15,
    feeUsing: 'taker', // maker || taker

  },

```

I don't have any particular problem with my gekko process, I tested several backtests with this set of data and didn't get any issue 🤔 

It seems to happen when using > 1months set of data. I tried to use the same settings with a range limited to a couple of weeks and it worked.

Thanks !

**Comment by generalectric** [comment]
Edit gekko/web/vue/UIconfig.js and adjust your timeout setting to give it more time. Restart server.js and try again.

**Comment by fredericcambon** [comment]
Thanks a lot !

**Comment by MickeySaeys** [comment]
@generalectric Do I need to add timeout setting? This is my current js file: 

// This config is used in both the
// frontend as well as the web server.

// see https://github.com/askmike/gekko/blob/stable/docs/installing_gekko_on_a_server.md

const CONFIG = {
  headless: true,
  api: {
      host: '0.0.0.0',
      port: 3000,
  },
  ui: {
      ssl: false,
      host: '192.168.1.20', // Set this to the IP of the machine that will run Gekko
      port: 3000,
      path: '/'
  },
  adapter: 'sqlite'

}
if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by korn360** [comment]
hi there, you UIconfig file with the timeout settings:

// This config is used in both the
// frontend as well as the web server.

// see https://github.com/askmike/gekko/blob/stable/docs/installing_gekko_on_a_server.md

const CONFIG = {
  headless: false,
  api: {
    host: '127.0.0.1',
    port: 3000,
    timeout: 240000 // 4 minutes
  },
  ui: {
    ssl: false,
    host: 'localhost',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by MrBird77** [comment]
anyone still having issues after changing the timeout in uiconfig?
