### ISSUE TITLE
error with gekko 0.5.11 update

### ISSUE THREAD

**Issue by orangekj** [gekkowarez/gekkoga#11]
Hi gekkowarez,

gekkoga was running fine with 0.5.10 but with latest 0.5.11 update, gekkoga starting to throw errors.

gekkoga log:

/gekko/gekkoga# node run -c config/downtrend.js
Previous config found, loading...
Loaded previous config from downtrend-BTC_ETH.json
Resuming previous run...
Starting training with: 4 units
{ StatusCodeError: 500 - "Internal Server Error"
    at new StatusCodeError (/gekko/gekkoga/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/gekko/gekkoga/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/gekko/gekkoga/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/gekko/gekkoga/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',
  error: 'Internal Server Error',

gekko web server error:

Error: non-error thrown: Child process has died.
      at Object.onerror (/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by nickreese** [comment]
I've got the same issue.

**Comment by nickreese** [comment]
Switching from mongodb to sqlite fixed it for me.

**Comment by dwarda** [comment]
I am having the same error. 
can you guys explain how to fix it ?
thank you

**Comment by generalectric** [comment]
Internal 500 error this has been discussed numerous times here as well as discord chat. Going to close this up for now
