### ISSUE TITLE
StatusCodeError: 500 - "Internal Server Error"

### ISSUE THREAD

**Issue by oikonen** [gekkowarez/gekkoga#25]
I get these errors when trying to run Gekkoga

Terminal 2
```
No previous run data, starting from scratch!
Starting GA with epoch populations of 20, running 5 units at a time!
{ StatusCodeError: 500 - "Internal Server Error"
    at new StatusCodeError (/home/oikonen/gekko/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/oikonen/gekko/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/oikonen/gekko/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/oikonen/gekko/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/oikonen/gekko/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/oikonen/gekko/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',
  error: 'Internal Server Error',
  options:
   { url: 'http://localhost:3000/api/backtest',
     json: true,
     body: { gekkoConfig: [Object], data: [Object] },
     headers: { 'Content-Type': 'application/json' },
     timeout: 1200000,
     method: 'POST',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 942,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1671,
        _destroyed: false,
        [Symbol(asyncId)]: 23,
        [Symbol(bytesRead)]: 176,
        [Symbol(asyncId)]: 63,
        [Symbol(triggerAsyncId)]: 57 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 942,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1671,
        _destroyed: false,
        [Symbol(asyncId)]: 23,
        [Symbol(bytesRead)]: 176,
        [Symbol(asyncId)]: 63,
        [Symbol(triggerAsyncId)]: 57 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '21',
        date: 'Fri, 26 Jan 2018 11:31:13 GMT',
        connection: 'close' },
     rawHeaders:
      [ 'Content-Type',
        'text/plain; charset=utf-8',
        'Content-Length',
        '21',
        'Date',
        'Fri, 26 Jan 2018 11:31:13 GMT',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 500,
     statusMessage: 'Internal Server Error',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 942,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1671,
        _destroyed: false,
        [Symbol(asyncId)]: 23,
        [Symbol(bytesRead)]: 176,
        [Symbol(asyncId)]: 63,
        [Symbol(triggerAsyncId)]: 57 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /api/backtest HTTP/1.1\r\nContent-Type: application/json\r\nhost: localhost:3000\r\naccept: application/json\r\ncontent-length: 791\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/backtest',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        body: '{"gekkoConfig":{"watch":{"exchange":"binance","currency":"BTC","asset":"ETH"},"paperTrader":{"slippage":0.05,"feeTaker":0.1,"feeMaker":0.1,"feeUsing":"taker","simulationBalance":{"asset":1,"currency":1},"reportRoundtrips":true,"enabled":true},"writer":{"enabled":false,"logpath":""},"tradingAdvisor":{"enabled":true,"method":"StochRSI_MACD","candleSize":60,"historySize":31},"trader":{"enabled":false},"backtest":{"daterange":"scan"},"performanceAnalyzer":{"riskFreeReturn":5,"enabled":true},"valid":true,"StochRSI_MACD":{"historySize":31,"short":8,"long":17,"signal":7,"up":"0.000000081","down":"-0.000000383","persistence":5,"low":30,"high":72,"interval":1,"candleSize":60}},"data":{"candleProps":["close","start"],"indicatorResults":false,"report":true,"roundtrips":false,"trades":false}}',
        headers: [Object],
        timeout: 1200000,
        method: 'POST',
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Object],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Object],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '3000',
        host: 'localhost',
        path: '/api/backtest',
        _json: true,
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://localhost:3000/api/backtest',
        req: [Object],
        ntick: true,
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'localhost:3000',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 'Internal Server Error' } }

   ```

Terminal 1
```
2018-01-26 13:31:13 (INFO):              Trading Advisor
/home/oikonen/gekko/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'up' of undefined
    at Base.method.check (/home/oikonen/gekko/strategies/StochRSI_MACD.js:79:56)
    at Base.bound [as check] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.propogateTick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:233:10)
    at Base.bound [as propogateTick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.tick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:150:10)
    at Base.bound [as tick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/oikonen/gekko/plugins/tradingAdvisor/tradingAdvisor.js:79:15)
    at CandleBatcher.bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at CandleBatcher.emit (events.js:211:7)
--> in Database#all('\n    SELECT * from candles_BTC_ETH\n    WHERE start <= 1500037799 AND start >= 1500034800\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/home/oikonen/gekko/plugins/sqlite/reader.js:98:11)
    at Reader.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/home/oikonen/gekko/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/home/oikonen/gekko/core/markets/backtest.js:105:10)
    at bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/oikonen/gekko/plugins/sqlite/reader.js:108:5)
2018-01-26 13:31:13 (INFO):              Calculate trading advice
/home/oikonen/gekko/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'up' of undefined
    at Base.method.check (/home/oikonen/gekko/strategies/StochRSI_MACD.js:79:56)
    at Base.bound [as check] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.propogateTick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:233:10)
    at Base.bound [as propogateTick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.tick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:150:10)
    at Base.bound [as tick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/oikonen/gekko/plugins/tradingAdvisor/tradingAdvisor.js:79:15)
    at CandleBatcher.bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at CandleBatcher.emit (events.js:211:7)
--> in Database#all('\n    SELECT * from candles_BTC_ETH\n    WHERE start <= 1500085799 AND start >= 1500082800\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/home/oikonen/gekko/plugins/sqlite/reader.js:98:11)
    at Reader.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/home/oikonen/gekko/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/home/oikonen/gekko/core/markets/backtest.js:105:10)
    at bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/oikonen/gekko/plugins/sqlite/reader.js:108:5)
2018-01-26 13:31:13 (INFO):              Using the strategy: StochRSI_MACD
2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):     Setting up:
2018-01-26 13:31:13 (INFO):              Paper Trader
2018-01-26 13:31:13 (INFO):              Paper trader that simulates fake trades.
/home/oikonen/gekko/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'up' of undefined
    at Base.method.check (/home/oikonen/gekko/strategies/StochRSI_MACD.js:79:56)
    at Base.bound [as check] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.propogateTick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:233:10)
    at Base.bound [as propogateTick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.tick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:150:10)
    at Base.bound [as tick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/oikonen/gekko/plugins/tradingAdvisor/tradingAdvisor.js:79:15)
    at CandleBatcher.bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at CandleBatcher.emit (events.js:211:7)
--> in Database#all('\n    SELECT * from candles_BTC_ETH\n    WHERE start <= 1500118799 AND start >= 1500115800\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/home/oikonen/gekko/plugins/sqlite/reader.js:98:11)
    at Reader.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/home/oikonen/gekko/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/home/oikonen/gekko/core/markets/backtest.js:105:10)
    at bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/oikonen/gekko/plugins/sqlite/reader.js:108:5)
2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):     Setting up:
2018-01-26 13:31:13 (INFO):              Performance Analyzer
2018-01-26 13:31:13 (INFO):              Analyzes performances of trades
2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):     Setting up:
2018-01-26 13:31:13 (INFO):              Paper Trader
2018-01-26 13:31:13 (INFO):              Paper trader that simulates fake trades.
2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):     Setting up:
2018-01-26 13:31:13 (INFO):              Performance Analyzer
2018-01-26 13:31:13 (INFO):              Analyzes performances of trades
2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):     Scanning local history for backtestable dateranges.
2018-01-26 13:31:13 (DEBUG):    Available 281940
2018-01-26 13:31:13 (DEBUG):    Optimal 281939
2018-01-26 13:31:13 (INFO):     Gekko is able to fully use the local history.
2018-01-26 13:31:13 (INFO):     Gekko was able to find a single daterange in the locally stored history:
2018-01-26 13:31:13 (INFO):              from: 2017-07-14 04:00:00
2018-01-26 13:31:13 (INFO):              to: 2018-01-25 22:59:00
2018-01-26 13:31:13 (INFO):             WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
2018-01-26 13:31:13 (INFO):             WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!
2018-01-26 13:31:13 (DEBUG):    calculated StochRSI properties for candle:
2018-01-26 13:31:13 (DEBUG):             rsi: 26.09637070
2018-01-26 13:31:13 (DEBUG):    StochRSI min:           14.22780031
2018-01-26 13:31:13 (DEBUG):    StochRSI max:           44.69161716
2018-01-26 13:31:13 (DEBUG):    StochRSI Value:         38.96
2018-01-26 13:31:13 (DEBUG):    calculated MACD properties for candle:
2018-01-26 13:31:13 (DEBUG):             short: 0.08804481
2018-01-26 13:31:13 (DEBUG):             long: 0.08786576
2018-01-26 13:31:13 (DEBUG):             macd: 0.00017905
2018-01-26 13:31:13 (DEBUG):             signal: 0.00069582
2018-01-26 13:31:13 (DEBUG):             macdiff: -0.00051677
2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):     Setting up:
2018-01-26 13:31:13 (INFO):              Performance Analyzer
2018-01-26 13:31:13 (INFO):              Analyzes performances of trades
2018-01-26 13:31:13 (INFO):

2018-01-26 13:31:13 (INFO):     Scanning local history for backtestable dateranges.
2018-01-26 13:31:13 (DEBUG):    Available 281940
2018-01-26 13:31:13 (DEBUG):    Optimal 281939
2018-01-26 13:31:13 (INFO):     Gekko is able to fully use the local history.
2018-01-26 13:31:13 (INFO):     Gekko was able to find a single daterange in the locally stored history:
2018-01-26 13:31:13 (INFO):              from: 2017-07-14 04:00:00
2018-01-26 13:31:13 (INFO):              to: 2018-01-25 22:59:00
2018-01-26 13:31:13 (INFO):             WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
2018-01-26 13:31:13 (INFO):             WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!
2018-01-26 13:31:13 (DEBUG):    calculated StochRSI properties for candle:
2018-01-26 13:31:13 (DEBUG):             rsi: 88.80666015
2018-01-26 13:31:13 (DEBUG):    StochRSI min:           79.35127642
2018-01-26 13:31:13 (DEBUG):    StochRSI max:           89.00618820
2018-01-26 13:31:13 (DEBUG):    StochRSI Value:         97.93
2018-01-26 13:31:13 (DEBUG):    calculated MACD properties for candle:
2018-01-26 13:31:13 (DEBUG):             short: 0.09031696
2018-01-26 13:31:13 (DEBUG):             long: 0.08947514
2018-01-26 13:31:13 (DEBUG):             macd: 0.00084182
2018-01-26 13:31:13 (DEBUG):             signal: 0.00065743
2018-01-26 13:31:13 (DEBUG):             macdiff: 0.00018439
2018-01-26 13:31:13 (INFO):     Scanning local history for backtestable dateranges.
2018-01-26 13:31:13 (DEBUG):    Available 281940
2018-01-26 13:31:13 (DEBUG):    Optimal 281939
2018-01-26 13:31:13 (INFO):     Gekko is able to fully use the local history.
2018-01-26 13:31:13 (INFO):     Gekko was able to find a single daterange in the locally stored history:
2018-01-26 13:31:13 (INFO):              from: 2017-07-14 04:00:00
2018-01-26 13:31:13 (INFO):              to: 2018-01-25 22:59:00
2018-01-26 13:31:13 (INFO):             WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
2018-01-26 13:31:13 (INFO):             WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!
2018-01-26 13:31:13 (DEBUG):    calculated StochRSI properties for candle:
2018-01-26 13:31:13 (DEBUG):             rsi: 100.00000000
2018-01-26 13:31:13 (DEBUG):    StochRSI min:           100.00000000
2018-01-26 13:31:13 (DEBUG):    StochRSI max:           100.00000000
2018-01-26 13:31:13 (DEBUG):    StochRSI Value:         NaN
2018-01-26 13:31:13 (DEBUG):    calculated MACD properties for candle:
2018-01-26 13:31:13 (DEBUG):             short: 0.09173718
2018-01-26 13:31:13 (DEBUG):             long: 0.09085331
2018-01-26 13:31:13 (DEBUG):             macd: 0.00088387
2018-01-26 13:31:13 (DEBUG):             signal: 0.00093745
2018-01-26 13:31:13 (DEBUG):             macdiff: -0.00005358
2018-01-26 13:31:13 (INFO):     Scanning local history for backtestable dateranges.
2018-01-26 13:31:13 (DEBUG):    Available 281940
2018-01-26 13:31:13 (DEBUG):    Optimal 281939
2018-01-26 13:31:13 (INFO):     Gekko is able to fully use the local history.
2018-01-26 13:31:13 (INFO):     Gekko was able to find a single daterange in the locally stored history:
2018-01-26 13:31:13 (INFO):              from: 2017-07-14 04:00:00
2018-01-26 13:31:13 (INFO):              to: 2018-01-25 22:59:00
2018-01-26 13:31:13 (INFO):             WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
2018-01-26 13:31:13 (INFO):             WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!
  xxx POST /api/backtest 500 1,184ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/oikonen/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/backtest 500 1,130ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/oikonen/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/backtest 500 1,099ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/oikonen/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

2018-01-26 13:31:14 (DEBUG):    calculated StochRSI properties for candle:
2018-01-26 13:31:14 (DEBUG):             rsi: 54.11224964
/home/oikonen/gekko/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'up' of undefined
    at Base.method.check (/home/oikonen/gekko/strategies/StochRSI_MACD.js:79:56)
    at Base.bound [as check] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.propogateTick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:233:10)
    at Base.bound [as propogateTick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.tick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:150:10)
    at Base.bound [as tick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/oikonen/gekko/plugins/tradingAdvisor/tradingAdvisor.js:79:15)
    at CandleBatcher.bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at CandleBatcher.emit (events.js:211:7)
--> in Database#all('\n    SELECT * from candles_BTC_ETH\n    WHERE start <= 1500523799 AND start >= 1500520800\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/home/oikonen/gekko/plugins/sqlite/reader.js:98:11)
    at Reader.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/home/oikonen/gekko/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/home/oikonen/gekko/core/markets/backtest.js:105:10)
    at bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/oikonen/gekko/plugins/sqlite/reader.js:108:5)
2018-01-26 13:31:14 (DEBUG):    StochRSI min:           4.00676355
2018-01-26 13:31:14 (DEBUG):    StochRSI max:           54.11224964
2018-01-26 13:31:14 (DEBUG):    StochRSI Value:         100.00
2018-01-26 13:31:14 (DEBUG):    calculated MACD properties for candle:
2018-01-26 13:31:14 (DEBUG):             short: 0.09348475
2018-01-26 13:31:14 (DEBUG):             long: 0.09252072
2018-01-26 13:31:14 (DEBUG):             macd: 0.00096403
2018-01-26 13:31:14 (DEBUG):             signal: 0.00132428
2018-01-26 13:31:14 (DEBUG):             macdiff: -0.00036025
  xxx POST /api/backtest 500 1,633ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/oikonen/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

2018-01-26 13:31:14 (DEBUG):    calculated StochRSI properties for candle:
2018-01-26 13:31:14 (DEBUG):             rsi: 42.74704366
2018-01-26 13:31:14 (DEBUG):    StochRSI min:           27.68607296
2018-01-26 13:31:14 (DEBUG):    StochRSI max:           55.40647411
2018-01-26 13:31:14 (DEBUG):    StochRSI Value:         54.33
2018-01-26 13:31:14 (DEBUG):    calculated MACD properties for candle:
2018-01-26 13:31:14 (DEBUG):             short: 0.09378403
2018-01-26 13:31:14 (DEBUG):             long: 0.09096356
2018-01-26 13:31:14 (DEBUG):             macd: 0.00282047
/home/oikonen/gekko/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'up' of undefined
    at Base.method.check (/home/oikonen/gekko/strategies/StochRSI_MACD.js:79:56)
    at Base.bound [as check] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.propogateTick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:233:10)
    at Base.bound [as propogateTick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.tick (/home/oikonen/gekko/plugins/tradingAdvisor/baseTradingMethod.js:150:10)
    at Base.bound [as tick] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/oikonen/gekko/plugins/tradingAdvisor/tradingAdvisor.js:79:15)
    at CandleBatcher.bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at CandleBatcher.emit (events.js:211:7)
--> in Database#all('\n    SELECT * from candles_BTC_ETH\n    WHERE start <= 1500523799 AND start >= 1500520800\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/home/oikonen/gekko/plugins/sqlite/reader.js:98:11)
    at Reader.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/home/oikonen/gekko/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/home/oikonen/gekko/core/markets/backtest.js:105:10)
    at bound (/home/oikonen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/oikonen/gekko/plugins/sqlite/reader.js:108:5)
2018-01-26 13:31:14 (DEBUG):             signal: 0.00358610
2018-01-26 13:31:14 (DEBUG):             macdiff: -0.00076563
  xxx POST /api/backtest 500 1,654ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/oikonen/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

My config

```
 candleValues: [5,10,15,30,60,120,240],
  getProperties: () => ({
    // Strat settings must be flattened and cannot be nested for mutation to work properly!

    historySize: randomExt.integer(100, 20),

    short: randomExt.integer(15,5),
    long: randomExt.integer(40,15),
    signal: randomExt.integer(12,6),
    up: randomExt.float(0.0000005,0).toFixed(9),
    down: randomExt.float(0,-0.0000005).toFixed(9),
	persistence: randomExt.integer(10,0),
	low: randomExt.integer(30,5),
    high: randomExt.integer(80,60),
    interval: randomExt.integer(8,1),
   	

    candleSize: config.candleValues[randomExt.integer(config.candleValues.length -1, 0)]

```

**Comment by oikonen** [comment]
Problem solved. The issue was in config.

**Comment by generalectric** [comment]
Up is not defined.. Did you change the variable names in the strat to match gekkoga flattened variables? And I'm assuming you fed the settings to addindicator as an object? addindicator('macd','MACD', {long: settings.macd_long, etc})? Let me know if you any questions or need help.

**Comment by 0xPBIT** [comment]
I am getting this issue as well. I don't know what is wrong with my setup. When I try to run:
`$ node -–max-old-space-size=8192 server.js`
I get:
`node: bad option: -–max-old-space-size=8192`

The console says it's setting up Gekko backtester and then it prints:
`node(30508,0x7fffad5fa380) malloc: *** mach_vm_map(size=18446744073709543424) failed (error code=3)
*** error: can't allocate region`
a bunch of times. 

The config that replaces sample-config from cloning the repo is supposed to stay inside gekkoga/config correct?

**Comment by 0xPBIT** [comment]
The Gekko server also continually runs backtests. 

But the GA output is:

`No previous run data, starting from scratch!
Starting GA with epoch populations of 20, running 5 units at a time!
{ StatusCodeError: 500 - "Internal Server Error"
    at new StatusCodeError (/Users/prestonbrown/gekko/gekkoga/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/prestonbrown/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/prestonbrown/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/prestonbrown/gekko/gekkoga/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/prestonbrown/gekko/gekkoga/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/prestonbrown/gekko/gekkoga/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',`

**Comment by Flowinger** [comment]
@oikonen "Problem solved. The issue was in config." care to say what the issue was?
