### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by oikonen** [gekkowarez/gekkoga#27]
Any Idea What's wrong here?

```
/home/oikonen/gekko/gekkoga/config/RSIMACD.js:73
    candleSize: config.candleValues[randomExt.integer(config.candleValues.length -1, 0)]
    ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/oikonen/gekko/gekkoga/run.js:16:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```
Here is my config 
```
 candleValues: [5,10,15,30,60], //,120,240],
  getProperties: () => ({
    // Strat settings must be flattened and cannot be nested for mutation to work properly!

    historySize: randomExt.integer(100, 10),
    interval: randomExt.integer(8, 1),
    short: randomExt.integer(15, 5),
    long: randomExt.integer(30, 15),
    signal:randomExt.integer(12, 4),
    up: randomExt.float(0.0002, 0).toFixed(5),
    down: randomExt.float(0, -0.0002).toFixed(5),
    low: randomExt.integer(30, 5),
    high: randomExt.integer(80, 60),
    persistence: randomExt.integer(10, 0)
    candleSize: config.candleValues[randomExt.integer(config.candleValues.length -1, 0)]

  })
};

```

**Comment by generalectric** [comment]
Missing comma after persistence

    persistence: randomExt.integer(10, 0),
