### ISSUE TITLE
StatusCodeError: 500 - "Internal Server Error"

### ISSUE THREAD

**Issue by elmolinger** [gekkowarez/gekkoga#33]
i have got following error when trying to run gekkoga using any strat
also tried macd strat.

Gekko
```
StatusCodeError: 500 - "Internal Server Error 
```

GA
``` 
xxx POST /api/backtest 500 302ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

```
node run.js -c config/your-new.js
No previous run data, starting from scratch!
Starting GA with epoch populations of 20, running 8 units at a time!
{ StatusCodeError: 500 - "Internal Server Error"
    at new StatusCodeError (/home/elmolinger/gekko/gekkoga/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/elmolinger/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/elmolinger/gekko/gekkoga/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/elmolinger/gekko/gekkoga/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/elmolinger/gekko/gekkoga/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/elmolinger/gekko/gekkoga/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',
  error: 'Internal Server Error',
  options:
   { url: 'http://localhost:3000/api/backtest',
     json: true,
     body: { gekkoConfig: [Object], data: [Object] },
     headers: { 'Content-Type': 'application/json' },
     timeout: 1200000,
     method: 'POST',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 1055,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 809,
        _destroyed: false,
        [Symbol(asyncId)]: 28,
        [Symbol(bytesRead)]: 176,
        [Symbol(asyncId)]: 86,
        [Symbol(triggerAsyncId)]: 82 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 1055,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 809,
        _destroyed: false,
        [Symbol(asyncId)]: 28,
        [Symbol(bytesRead)]: 176,
        [Symbol(asyncId)]: 86,
        [Symbol(triggerAsyncId)]: 82 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '21',
        date: 'Sun, 25 Feb 2018 21:20:23 GMT',
        connection: 'close' },
     rawHeaders:
      [ 'Content-Type',
        'text/plain; charset=utf-8',
        'Content-Length',
        '21',
        'Date',
        'Sun, 25 Feb 2018 21:20:23 GMT',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 500,
     statusMessage: 'Internal Server Error',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 1055,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 809,
        _destroyed: false,
        [Symbol(asyncId)]: 28,
        [Symbol(bytesRead)]: 176,
        [Symbol(asyncId)]: 86,
        [Symbol(triggerAsyncId)]: 82 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /api/backtest HTTP/1.1\r\nContent-Type: application/json\r\nhost: localhost:3000\r\naccept: application/json\r\ncontent-length: 904\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/backtest',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        body: '{"gekkoConfig":{"watch":{"exchange":"bitfinex","currency":"USD","asset":"LTC"},"paperTrader":{"slippage":0.05,"feeTaker":0.25,"feeMaker":0.15,"feeUsing":"taker","simulationBalance":{"asset":0,"currency":100},"reportRoundtrips":true,"enabled":true},"writer":{"enabled":false,"logpath":""},"tradingAdvisor":{"enabled":true,"method":"RSI_Bull_Bear_Adx","candleSize":20,"historySize":100},"trader":{"enabled":false},"backtest":{"daterange":{"from":"2017-08-25 14:10:00","to":"2017-11-11107:10:41"}},"performanceAnalyzer":{"riskFreeReturn":5,"enabled":true},"valid":true,"RSI_Bull_Bear_Adx":{"historySize":100,"SMA_long":1300,"SMA_short":44,"BULL_RSI":9,"BULL_RSI_high":70,"BULL_RSI_low":55,"BEAR_RSI":17,"BEAR_RSI_high":59,"BEAR_RSI_low":11,"ADX":2,"ADX_high":77,"ADX_low":44,"candleSize":20}},"data":{"candleProps":["close","start"],"indicatorResults":false,"report":true,"roundtrips":false,"trades":false}}',
        headers: [Object],
        timeout: 1200000,
        method: 'POST',
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Object],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Object],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '3000',
        host: 'localhost',
        path: '/api/backtest',
        _json: true,
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://localhost:3000/api/backtest',
        req: [Object],
        ntick: true,
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'localhost:3000',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     `body:` 'Internal Server Error' } }
```

```
2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
  xxx POST /api/backtest 500 394ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/backtest 500 336ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/backtest 500 302ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/backtest 500 262ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/backtest 500 234ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  xxx POST /api/backtest 500 205ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
  xxx POST /api/backtest 500 206ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

2018-02-25 22:20:23 (INFO):     Setting up Gekko in backtest mode
2018-02-25 22:20:23 (INFO):
2018-02-25 22:20:23 (INFO):     Setting up:
2018-02-25 22:20:23 (INFO):              Trading Advisor
2018-02-25 22:20:23 (INFO):              Calculate trading advice
  xxx POST /api/backtest 500 212ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/elmolinger/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)```

**Comment by sameerk-k** [comment]
I am getting the same error.

**Comment by goldistan** [comment]
same here, even after flattening the parameters as suggested in other threads.

**Comment by sameerk-k** [comment]
The flattening works and resolves the primary issue. I was able to resolve the Internal Server error by making sure the date range of the backtest data matched the config date range precisely. Also, check the strat for any reference to the unflattened parameters.

**Comment by generalectric** [comment]
We currently have experimental nested object support. I say experimental because it did not fully work for me and I went back to flattened vars. If you have incorrect date range not matching data... Or strat name and file name mismatch you will get no error at all... Only a 500 internal server error. If your data and strat name configs are good you will have error output from your strat

**Comment by generalectric** [comment]
#30
